server:
  port: 80
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource            # 当前数据源操作类型
    driver-class-name: com.mysql.cj.jdbc.Driver              # mysql驱动包
    url: jdbc:mysql://47.107.249.42:3306/demo?serverTimezone=GMT%2B8&useSSL=false             # 数据库名称
    username: root
    password: root
  thymeleaf:
    encoding: utf-8
    suffix: .html
    cache: false
  redis:
    host: 47.107.249.42
    port: 6379
  mvc:
    hiddenmethod:
      filter:
        enabled: true
  security:
    user:
      name: tianling
      password: 123
  session:
    store-type: redis
    timeout: 10000
security:
  oauth2:
    client:
      client-id: tianling
      client-secret: 123456
      registered-redirect-uri:
        - http://www.pinzhi365.com
my:
  security:
    code:
      image:
        length: 6
        urls: /user,/user/*
    social:
      qq:
        app-id: 100550231
        app-secret: 69b6ab57b22f3c2fe6a6149274e3295e
        providerId: callback.do
      filterProcessesUrl: /qqLogin
      vx:
        app-id: wxd99431bbff8305a0
        app-secret: 60f78681d063590a469f1b297feff3c4
